[package]
name = "engine"
version = "0.1.0"
authors = ["Austin <me@austinj.me>"]

[dependencies]
vulkano = { path = "./vulkano/vulkano" }
vulkano-win = { path = "./vulkano/vulkano-win" }
vulkano-shaders = { path = "./vulkano/vulkano-shaders" }
image = "=0.19.0"
rand = "=0.4.2"
parking_lot = "=0.5.5"
crossbeam = "0.5.0"
num_cpus = "=1.8.0"
winit = "0.18.0"
decorum = "0.1.1"
freetype = "0.4.1"
