[package]
name = "basalt"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]

[dependencies]
vulkano = { path = "./vulkano/vulkano" }
vulkano-win = { path = "./vulkano/vulkano-win" }
vulkano-shaders = { path = "./vulkano/vulkano-shaders" }
image = "0.20.1"
rand = "0.6.1"
parking_lot = "0.7.1"
crossbeam = "0.7.1"
num_cpus = "1.9.0"
winit = "0.19.0"
decorum = "0.1.2"
freetype-sys = "0.7.1"
curl = "0.4.19"

