[package]
name = "engine"
version = "0.1.0"
authors = ["Austin <me@austinj.me>"]

[dependencies]
vulkano = { path = "./vulkano/vulkano" }
vulkano-win = { path = "./vulkano/vulkano-win" }
vulkano-shaders = { path = "./vulkano/vulkano-shaders" }
cgmath = "=0.16.1"
image = "=0.19.0"
rand = "=0.4.2"
parking_lot = "=0.5.5"
crossbeam = "=0.3.2"
num_cpus = "=1.8.0"
winit = "=0.17.2"
serde = "=1.0.55"
serde_derive = "=1.0.55"
bincode = "=0.9.2"
decorum = "0.1.1"
harfbuzz-sys = "0.3.0"
freetype = "0.4.1"
