[package]
name = "engine"
version = "0.1.0"
authors = ["Austin <me@austinj.me>"]

[dependencies]
vulkano = { path = "./vulkano/vulkano" }
vulkano-shader-derive = { path = "./vulkano/vulkano-shader-derive" }
vulkano-win = { path = "./vulkano/vulkano-win" }
cgmath = "0.15.0"
image = "0.15.0"
rand = "0.3.17"
parking_lot = "0.4.8"
noise = "0.4.1"
crossbeam = "0.3.0"
freetype-sys = "0.5.0"
num_cpus = "1.7.0"
winit = "=0.11.1"
serde = "1.0.15"
serde_derive = "1.0.15"
bincode = "0.9.1"

