[package]
name = "basalt"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
repository = "https://bitbucket.org/AustinJ235/basalt"
description = "A window/ui framework built upon vulkan."
license = "MIT"
keywords = ["vulkan", "graphics", "gui", "framework", "ui", "interface"]
categories = ["graphics","gui",]
readme = "./README.md"

[dependencies]
vulkano = { version = "0.11.1", path = "./vulkano/vulkano"}
vulkano-win = { version = "0.11.1", path = "./vulkano/vulkano-win" }
vulkano-shaders = { version = "0.11.1", path = "./vulkano/vulkano-shaders" }
image = "0.20.1"
rand = "0.6.1"
parking_lot = "0.7.1"
crossbeam = "0.7.1"
num_cpus = "1.9.0"
winit = "0.19.1"
decorum = "0.1.2"
freetype-sys = "0.7.1"
curl = "0.4.19"

