[package]
name = "engine"
version = "0.1.0"
authors = ["Austin <me@austinj.me>"]

[dependencies]
vulkano = { path = "./vulkano/vulkano" }
vulkano-shader-derive = { path = "./vulkano/vulkano-shader-derive" }
vulkano-win = { path = "./vulkano/vulkano-win" }
cgmath = "=0.16.1"
image = "=0.19.0"
rand = "=0.4.2"
parking_lot = "=0.5.5"
crossbeam = "=0.3.2"
freetype-sys = "=0.7.0"
num_cpus = "=1.8.0"
winit = "=0.17.2"
serde = "=1.0.55"
serde_derive = "=1.0.55"
bincode = "=0.9.2"

